before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/qasm
    binary: qasm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/orangekame3/qasmtools/cmd.Version={{.Version}}
      - -X github.com/orangekame3/qasmtools/cmd.Commit={{.Commit}}
      - -X github.com/orangekame3/qasmtools/cmd.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: orangekame3
      name: homebrew-tap
    homepage: "https://github.com/orangekame3/qasmtools"
    description: "QASM tools for formatting and parsing QASM files"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "qasm"
    test: |
      system "#{bin}/qasm", "--version"

dockers:
  - image_templates:
      - "ghcr.io/orangekame3/qasmtools:{{ .Version }}"
      - "ghcr.io/orangekame3/qasmtools:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
