version: 2

project_name: qasmtools

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/qasm
    binary: qasm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'



changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: orangekame3
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/orangekame3/qasmtools"
    description: "QASM tools for formatting, linting, and parsing OpenQASM 3.0 files"
    license: "Apache-2.0"
    test: |
      system "#{bin}/qasm", "--version"

dockers:
  - image_templates:
      - "ghcr.io/orangekame3/qasmtools:{{ .Version }}"
      - "ghcr.io/orangekame3/qasmtools:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/orangekame3/qasmtools"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
